version: "2.4"
services:
  dev:
    image: ruby:2.7
    working_dir: /work
    volumes:
    - .:/work
    - ruby2.7-bundle-cache:/usr/local/bundle

volumes:
  ruby2.7-bundle-cache:
    external: true
